sudo: required # 관리자권한 갖기

language: generic # 언어(플랫폼) 선택

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -f Dockerfile.dev -t bonzoman/docker-react-app ./

script:
  - docker run -e CI=true bonzoman/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"
