sudo: required # 관리자권한 갖기

language: generic # 언어(플랫폼) 선택

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -f Dockerfile.dev -t bonzoman/docker-react-app ./

script:
  - docker run -e CI=true bonzoman/docker-react-app npm run test -- --coverage

# aws의 Elastic Beanstalk을 통해 등록된 정보 기입
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "Docker-React-App2"
  env: "Docker-React-App2-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-561298026791"
  bucket_path: "Docker-React-App2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  


# after_success:
#   - echo "Test Success"
